// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2XCpnMNn4tbvYsmdJdruDGew1BhCBIdw',
    appId: '1:152494983161:web:015eb45efd82a5f99fdf28',
    messagingSenderId: '152494983161',
    projectId: 'firbasestudycase',
    authDomain: 'firbasestudycase.firebaseapp.com',
    storageBucket: 'firbasestudycase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPE3H6mKcVH42vzWEJ68IJwbuQ-PYk-IQ',
    appId: '1:152494983161:android:2f1a4b33756d24b69fdf28',
    messagingSenderId: '152494983161',
    projectId: 'firbasestudycase',
    storageBucket: 'firbasestudycase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTzcw6EsSbsqsoHF-Ty6RFTQFaZ5UFdag',
    appId: '1:152494983161:ios:e13ab3ea923146ac9fdf28',
    messagingSenderId: '152494983161',
    projectId: 'firbasestudycase',
    storageBucket: 'firbasestudycase.appspot.com',
    iosClientId: '152494983161-hlp8qc0v31c448ioph8u6j4rlrddljk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.studycase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTzcw6EsSbsqsoHF-Ty6RFTQFaZ5UFdag',
    appId: '1:152494983161:ios:9c41a85133184d8a9fdf28',
    messagingSenderId: '152494983161',
    projectId: 'firbasestudycase',
    storageBucket: 'firbasestudycase.appspot.com',
    iosClientId: '152494983161-8f54u4mcom3kgmllnuvnpioaou0vc0b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.studycase2.RunnerTests',
  );
}
